# Generated by Django 5.2.7 on 2025-10-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte')], max_length=2)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('regimen', models.CharField(default='FOMAG', max_length=50)),
            ],
        ),
    ]
