# Generated by Django 5.2.7 on 2025-11-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('codigo_producto', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripcion_producto', models.TextField()),
                ('farmacia', models.TextField()),
                ('direccion', models.CharField(max_length=80)),
                ('cantidad', models.IntegerField()),
                ('fecha_actualizacion', models.TimeField(auto_now=True)),
            ],
        ),
    ]
