# Generated by Django 5.2.7 on 2025-11-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_medicamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
