# Generated by Django 5.2.7 on 2025-11-09 23:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_medicamento_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
