# Generated by Django 5.2.7 on 2025-11-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_medicamento_fecha_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
