# Generated by Django 5.2.7 on 2025-11-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_medicamento_fecha_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='gramaje',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
